---
title: "Influenza A H7N9 in China, 2013"
author: "Seydou TOGUIYENI"
format: dashboard
theme: lux
---

```{r}
# Load packages 
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, outbreaks, bslib, bsicons, shiny, 
               rgeoboundaries, plotly, htmltools, reactable)

# view data
#head(outbreaks::fluH7N9_china_2013)

```


```{r}
# value_box1
total_cases <- fluH7N9_china_2013 %>%
                    summarise(total_cases = n()) %>%
                    pull(total_cases)
# value_box2
total_hospitalizations <- fluH7N9_china_2013 %>%
                                  filter(!is.na(date_of_hospitalisation)) %>%
                                  summarise(total_hospitalizations = n()) %>%
                                  pull(total_hospitalizations)

#value_box3
total_deaths <- fluH7N9_china_2013 %>%
                                  filter(outcome == "Death") %>%
                                  summarise(total_deaths = n()) %>%
                                  pull(total_deaths)
```


```{r}
# graph Number of Cases by province
cases_by_provinces <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) %>%
  arrange(desc(total_cases)) %>% 
  mutate(tooltip_label = paste(province, total_cases, sep = ": ")) %>% 
  ggplot(aes(y = reorder(province, total_cases), 
             x = total_cases, 
             text = tooltip_label)) + 
  geom_col(fill = "#386DA5") + 
  labs(x = "Number of Cases", y="") + 
  theme(legend.position = "none")+
  theme_minimal()

cases_by_provinces_ggplotly <- 
  ggplotly(cases_by_provinces, tooltip = "text")
```



```{r results='hide', message=FALSE, warning = FALSE}
### MAP OF CASES PER PROVINCE
province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) 

china_map <- rgeoboundaries::gb_adm1("china")

# Check the keys to see if join will be successful
setdiff(province_summary$province, china_map$shapeName)
setdiff(china_map$shapeName, province_summary$province)
# Some work to be done to harmonize these

china_map <- china_map %>%
  # Remove the strings Province, Municipality and Autonomous Region 
  # to allow matching
  mutate(province = str_trim(
    str_remove(shapeName, "Province|Municipality|Autonomous Region")
  ))

# Check if join will work fine
setdiff(province_summary$province, china_map$province)

# Fix Guangdong, which based on a quick Google is actually Guangzhou
china_map <- china_map %>% 
  mutate(province = if_else(province == "Guangzhou", "Guangdong", province)) 
  
# Check again
setdiff(province_summary$province, china_map$province)

# Now join
china_map_joined <- 
  left_join(china_map, province_summary, by = "province") %>% 
  # Create tooltip label 
  mutate(tooltip_label = paste0(province, ": ", total_cases))

china_map_plot <- ggplot(china_map_joined) +
  geom_sf(aes(fill = total_cases, text = tooltip_label)) + 
  theme_void() +
  labs(fill = "Number of Cases") + 
  theme(legend.position = "none")

china_map_plot_ggplotly <- 
  ggplotly(china_map_plot, tooltip = "text")
```



# HOME 

## Row1 {height=25%}

```{r}
# value box 1 : Total cases
value_box(
  title = "Total Cases",
  value = total_cases,
  showcase = bsicons::bs_icon("virus"),
  theme = value_box_theme(bg = "#518fd6")
)
```


```{r}
# value_box 2 : Total hospitalizations
value_box(
  title = "Total Hospitalizations",
  value = total_hospitalizations,
  showcase = bsicons::bs_icon("hospital"),
  theme = value_box_theme(bg = "#214773")
)
```


```{r}
# value_box 3 : Total Deaths
value_box(
  title = "Total Deaths",
  value = total_deaths,
  showcase = bsicons::bs_icon("heart-pulse"),
  theme = value_box_theme(bg = "#3f71ab")
)
```


## Row2

### {width=35%}

```{r title = "Number of Cases by Province"}
cases_by_provinces_ggplotly
```

###

```{r title = "Map of Province by Number of cases"}
china_map_plot_ggplotly
```


# DOWNLOAD DATA

```{r title = "The 2013 outbreak of influenza A H7N9 in China"}
htmltools::browsable(
  tagList(
    reactable(fluH7N9_china_2013, 
              elementId = "gapminder-table", 
              searchable = T, 
              filterable = T), 
    
tags$button("Download as CSV", 
            onclick = "Reactable.downloadDataCSV('gapminder-table')")
  )
)
```



